# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\addUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(638, 357)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelAddUserBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelAddUserBtn.setFont(font)
        self.cancelAddUserBtn.setStyleSheet("#cancelAddUserBtn{\n"
"    background-color: darkred;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.cancelAddUserBtn.setObjectName("cancelAddUserBtn")
        self.gridLayout.addWidget(self.cancelAddUserBtn, 5, 1, 1, 1)
        self.addUserDescriptionLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.addUserDescriptionLabel.setFont(font)
        self.addUserDescriptionLabel.setStyleSheet("#addUserDescriptionLabel{\n"
"    color: darkgreen;\n"
"    padding: 5px;\n"
"}")
        self.addUserDescriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addUserDescriptionLabel.setObjectName("addUserDescriptionLabel")
        self.gridLayout.addWidget(self.addUserDescriptionLabel, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 2)
        self.addUserTitleLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.addUserTitleLabel.setFont(font)
        self.addUserTitleLabel.setStyleSheet("#addUserTitleLabel{\n"
"    background-color: #670073;\n"
"    color: aliceblue;\n"
"}")
        self.addUserTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addUserTitleLabel.setObjectName("addUserTitleLabel")
        self.gridLayout.addWidget(self.addUserTitleLabel, 0, 0, 1, 2)
        self.submitUserBtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submitUserBtn.setFont(font)
        self.submitUserBtn.setStyleSheet("#submitUserBtn{\n"
"    background-color: darkgreen;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.submitUserBtn.setObjectName("submitUserBtn")
        self.gridLayout.addWidget(self.submitUserBtn, 5, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameField = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.usernameField.setFont(font)
        self.usernameField.setObjectName("usernameField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameField)
        self.password1Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password1Label.setFont(font)
        self.password1Label.setObjectName("password1Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password1Label)
        self.password1Field = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password1Field.setFont(font)
        self.password1Field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1Field.setObjectName("password1Field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password1Field)
        self.password2Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password2Label.setFont(font)
        self.password2Label.setObjectName("password2Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password2Label)
        self.password2Field = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password2Field.setFont(font)
        self.password2Field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2Field.setObjectName("password2Field")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password2Field)
        self.gridLayout.addLayout(self.formLayout, 3, 0, 1, 2)
        self.addUserError = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.addUserError.setFont(font)
        self.addUserError.setText("")
        self.addUserError.setAlignment(QtCore.Qt.AlignCenter)
        self.addUserError.setObjectName("addUserError")
        self.gridLayout.addWidget(self.addUserError, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelAddUserBtn.setText(_translate("Dialog", "CANCEL"))
        self.addUserDescriptionLabel.setText(_translate("Dialog", "You must create a user account to continue"))
        self.addUserTitleLabel.setText(_translate("Dialog", "ADD A NEW USER"))
        self.submitUserBtn.setText(_translate("Dialog", "ADD USER"))
        self.usernameLabel.setText(_translate("Dialog", "User "))
        self.password1Label.setText(_translate("Dialog", "Password "))
        self.password2Label.setText(_translate("Dialog", "Confirm Password "))
