# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\inventoryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inventoryDialog(object):
    def setupUi(self, inventoryDialog):
        inventoryDialog.setObjectName("inventoryDialog")
        inventoryDialog.resize(902, 761)
        self.gridLayout = QtWidgets.QGridLayout(inventoryDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.actionLayout = QtWidgets.QVBoxLayout()
        self.actionLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.actionLayout.setContentsMargins(0, -1, 0, -1)
        self.actionLayout.setSpacing(10)
        self.actionLayout.setObjectName("actionLayout")
        self.reloadInventory = QtWidgets.QPushButton(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reloadInventory.setFont(font)
        self.reloadInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reloadInventory.setStyleSheet("#reloadInventory{\n"
"    padding: 5px 10px;\n"
"    background-color: #333;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"}")
        self.reloadInventory.setObjectName("reloadInventory")
        self.actionLayout.addWidget(self.reloadInventory)
        self.addItemButton = QtWidgets.QPushButton(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addItemButton.setFont(font)
        self.addItemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addItemButton.setStyleSheet("#addItemButton{\n"
"    padding: 5px 10px;\n"
"    background-color: #670073;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"}")
        self.addItemButton.setObjectName("addItemButton")
        self.actionLayout.addWidget(self.addItemButton)
        self.deleteButton = QtWidgets.QPushButton(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteButton.setStyleSheet("#deleteButton{\n"
"    padding: 5px 10px;\n"
"    background-color: darkred;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"}")
        self.deleteButton.setObjectName("deleteButton")
        self.actionLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.actionLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.actionLayout, 4, 2, 1, 1)
        self.filterItemsField = QtWidgets.QLineEdit(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterItemsField.setFont(font)
        self.filterItemsField.setStyleSheet("#filterItemsField{\n"
"    padding: 5px;\n"
"}")
        self.filterItemsField.setObjectName("filterItemsField")
        self.gridLayout.addWidget(self.filterItemsField, 3, 0, 1, 2)
        self.errorField = QtWidgets.QLabel(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.errorField.setFont(font)
        self.errorField.setStyleSheet("#errorField{\n"
"    color: darkred;\n"
"}")
        self.errorField.setText("")
        self.errorField.setAlignment(QtCore.Qt.AlignCenter)
        self.errorField.setObjectName("errorField")
        self.gridLayout.addWidget(self.errorField, 0, 0, 1, 2)
        self.inventorySummaryLabel = QtWidgets.QLabel(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.inventorySummaryLabel.setFont(font)
        self.inventorySummaryLabel.setStyleSheet("#inventorySummaryLabel{\n"
"    padding: 5px 0px;\n"
"    color: #670073;\n"
"}")
        self.inventorySummaryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inventorySummaryLabel.setObjectName("inventorySummaryLabel")
        self.gridLayout.addWidget(self.inventorySummaryLabel, 1, 0, 1, 2)
        self.allItemsTable = QtWidgets.QTableWidget(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allItemsTable.setFont(font)
        self.allItemsTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allItemsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.allItemsTable.setAlternatingRowColors(True)
        self.allItemsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.allItemsTable.setObjectName("allItemsTable")
        self.allItemsTable.setColumnCount(7)
        self.allItemsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.allItemsTable.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.allItemsTable, 4, 0, 1, 2)
        self.inventoryCostLabel = QtWidgets.QLabel(inventoryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.inventoryCostLabel.setFont(font)
        self.inventoryCostLabel.setStyleSheet("#inventoryCostLabel{\n"
"    padding: 5px 0px;\n"
"    color: #670073;\n"
"}")
        self.inventoryCostLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inventoryCostLabel.setObjectName("inventoryCostLabel")
        self.gridLayout.addWidget(self.inventoryCostLabel, 2, 0, 1, 2)

        self.retranslateUi(inventoryDialog)
        QtCore.QMetaObject.connectSlotsByName(inventoryDialog)

    def retranslateUi(self, inventoryDialog):
        _translate = QtCore.QCoreApplication.translate
        inventoryDialog.setWindowTitle(_translate("inventoryDialog", "Dialog"))
        self.reloadInventory.setText(_translate("inventoryDialog", "Refresh"))
        self.addItemButton.setText(_translate("inventoryDialog", "Add Item"))
        self.deleteButton.setText(_translate("inventoryDialog", "Delete"))
        self.filterItemsField.setPlaceholderText(_translate("inventoryDialog", "Filter items"))
        self.inventorySummaryLabel.setText(_translate("inventoryDialog", "Total Inventory Amount: GHC 0.00"))
        self.allItemsTable.setSortingEnabled(True)
        item = self.allItemsTable.horizontalHeaderItem(0)
        item.setText(_translate("inventoryDialog", "#"))
        item = self.allItemsTable.horizontalHeaderItem(1)
        item.setText(_translate("inventoryDialog", "Item"))
        item = self.allItemsTable.horizontalHeaderItem(2)
        item.setText(_translate("inventoryDialog", "Description"))
        item = self.allItemsTable.horizontalHeaderItem(3)
        item.setText(_translate("inventoryDialog", "Cost Price"))
        item = self.allItemsTable.horizontalHeaderItem(4)
        item.setText(_translate("inventoryDialog", "Unit Price"))
        item = self.allItemsTable.horizontalHeaderItem(5)
        item.setText(_translate("inventoryDialog", "Quantity"))
        item = self.allItemsTable.horizontalHeaderItem(6)
        item.setText(_translate("inventoryDialog", "Amount"))
        self.inventoryCostLabel.setText(_translate("inventoryDialog", "Total Cost: GHC 0.00"))
