# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\paymentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paymentDialog(object):
    def setupUi(self, paymentDialog):
        paymentDialog.setObjectName("paymentDialog")
        paymentDialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(paymentDialog.sizePolicy().hasHeightForWidth())
        paymentDialog.setSizePolicy(sizePolicy)
        paymentDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(paymentDialog)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 35)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enterPaymentLabel = QtWidgets.QLabel(paymentDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterPaymentLabel.sizePolicy().hasHeightForWidth())
        self.enterPaymentLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.enterPaymentLabel.setFont(font)
        self.enterPaymentLabel.setStyleSheet("#enterPaymentLabel{\n"
"    color: #670073;\n"
"}")
        self.enterPaymentLabel.setObjectName("enterPaymentLabel")
        self.verticalLayout.addWidget(self.enterPaymentLabel)
        self.amountDueLabel = QtWidgets.QLabel(paymentDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amountDueLabel.setFont(font)
        self.amountDueLabel.setStyleSheet("#amountDueLabel{\n"
"    color: darkred;\n"
"}")
        self.amountDueLabel.setText("")
        self.amountDueLabel.setObjectName("amountDueLabel")
        self.verticalLayout.addWidget(self.amountDueLabel)
        self.paymentError = QtWidgets.QLabel(paymentDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paymentError.setFont(font)
        self.paymentError.setStyleSheet("#paymentError{\n"
"    color:darkred;\n"
"}")
        self.paymentError.setText("")
        self.paymentError.setAlignment(QtCore.Qt.AlignCenter)
        self.paymentError.setObjectName("paymentError")
        self.verticalLayout.addWidget(self.paymentError)
        self.lineEdit = QtWidgets.QLineEdit(paymentDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.payBtn = QtWidgets.QPushButton(paymentDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.payBtn.setFont(font)
        self.payBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payBtn.setStyleSheet("#payBtn{\n"
"    background-color: #ff6100;\n"
"    color: #670073;\n"
"    border: 1px solid #670073;\n"
"    border-radius:5px;\n"
"    padding: 5px;\n"
"}")
        self.payBtn.setObjectName("payBtn")
        self.horizontalLayout.addWidget(self.payBtn)
        self.cancelPayBtn = QtWidgets.QPushButton(paymentDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancelPayBtn.setFont(font)
        self.cancelPayBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelPayBtn.setStyleSheet("#cancelPayBtn{\n"
"    background-color: darkred;\n"
"    color: aliceblue;\n"
"    border: 1px solid darkred;\n"
"    border-radius:5px;\n"
"    padding: 5px;\n"
"}")
        self.cancelPayBtn.setObjectName("cancelPayBtn")
        self.horizontalLayout.addWidget(self.cancelPayBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(paymentDialog)
        QtCore.QMetaObject.connectSlotsByName(paymentDialog)

    def retranslateUi(self, paymentDialog):
        _translate = QtCore.QCoreApplication.translate
        paymentDialog.setWindowTitle(_translate("paymentDialog", "Dialog"))
        self.enterPaymentLabel.setText(_translate("paymentDialog", "Payment for Invoice GH378J"))
        self.payBtn.setText(_translate("paymentDialog", "PAY"))
        self.cancelPayBtn.setText(_translate("paymentDialog", "CANCEL"))
