# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\userLoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 356)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.loginErrorLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.loginErrorLabel.setFont(font)
        self.loginErrorLabel.setText("")
        self.loginErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginErrorLabel.setObjectName("loginErrorLabel")
        self.gridLayout.addWidget(self.loginErrorLabel, 1, 0, 1, 2)
        self.loginLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("#loginLabel{\n"
"    background-color: #670073;\n"
"    color: aliceblue;\n"
"}")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.gridLayout.addWidget(self.loginLabel, 0, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.loginUserLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginUserLabel.setFont(font)
        self.loginUserLabel.setObjectName("loginUserLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.loginUserLabel)
        self.loginUserField = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginUserField.setFont(font)
        self.loginUserField.setObjectName("loginUserField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginUserField)
        self.loginPasswordLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginPasswordLabel.setFont(font)
        self.loginPasswordLabel.setObjectName("loginPasswordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.loginPasswordLabel)
        self.loginPasswordField = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginPasswordField.setFont(font)
        self.loginPasswordField.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.loginPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPasswordField.setObjectName("loginPasswordField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loginPasswordField)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 2)
        self.cancelLoginButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelLoginButton.setFont(font)
        self.cancelLoginButton.setStyleSheet("#cancelLoginButton{\n"
"    background-color: darkred;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.cancelLoginButton.setObjectName("cancelLoginButton")
        self.gridLayout.addWidget(self.cancelLoginButton, 4, 1, 1, 1)
        self.loginButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("#loginButton{\n"
"    background-color: darkgreen;\n"
"    color: aliceblue;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginLabel.setText(_translate("Dialog", "LOGIN"))
        self.loginUserLabel.setText(_translate("Dialog", "User "))
        self.loginPasswordLabel.setText(_translate("Dialog", "Password "))
        self.cancelLoginButton.setText(_translate("Dialog", "CANCEL"))
        self.loginButton.setText(_translate("Dialog", "LOGIN"))
